---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-config
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-watch
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-downloads
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: fs
