---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: torrent
  name: torrent
  namespace: seedbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torrent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
      - image: docker.io/dperson/openvpn-client
        name: vpn
        args:
        - -r 10.0.0.0/8
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: "/dev/net/tun"
          name: tun
        - mountPath: "/vpn"
          name: torrent-vpn
      - image: docker.io/linuxserver/transmission
        name: torrent
        ports:
        - containerPort: 9091
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: "/config"
          name: torrent-config
        - mountPath: "/downloads"
          name: torrent-downloads
        - mountPath: "/watch"
          name: torrent-watch
      volumes:
      - name: torrent-config
        persistentVolumeClaim:
          claimName: torrent-config
      - name: torrent-watch
        persistentVolumeClaim:
          claimName: torrent-watch
      - name: torrent-downloads
        persistentVolumeClaim:
          claimName: torrent-downloads
      - name: torrent-vpn
        secret:
          secretName: vpn-secret
      - name: tun
        hostPath:
          path: "/dev/net/tun"
---
apiVersion: v1
kind: Service
metadata:
  name: torrent
  namespace: seedbox
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: torrent
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: torrent
  namespace: seedbox
spec:
  commonName: torrent.ptrk.io
  dnsNames:
  - torrent.ptrk.io
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  secretName: torrent
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: torrent
  namespace: seedbox
  annotations:
    cloudflare.com/expose: "true"
spec:
  virtualhost:
    fqdn: torrent.ptrk.io
    tls:
      secretName: torrent
    authorization:
      extensionRef:
        name: htpasswd
        namespace: projectcontour-auth
  routes:
  - services:
    - name: torrent
      port: 80
