---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resume
  name: resume
  namespace: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - image: docker.io/sh4d1/resume
        name: resume
        ports:
        - containerPort: 80
          name: http
