---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: contour
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    nameOverride: contour
    contour:
      manageCRDs: true
    envoy:
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
      useHostPort: true
      containerPorts:
        http: 8080
        https: 8443
