---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-movies
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-tvshows
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-config
  local:
    path: /data/seedbox/plex
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies
spec:
  capacity:
    storage: 512Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-movies
  local:
    path: /data/media/movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tvshows
spec:
  capacity:
    storage: 512Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-tvshows
  local:
    path: /data/media/tvshows
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: plex-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: plex-movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tvshows
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: plex-tvshows
