---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: plex-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-config
  local:
    path: /data/seedbox/plex
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies
  labels:
    juicefs-name: movies
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: media
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeAttributes:
      subPath: movies
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tvshows
  labels:
    juicefs-name: tvshows
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: media
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
    volumeAttributes:
      subPath: tvshows
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-all
  labels:
    juicefs-name: all
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: media
    fsType: juicefs
    nodePublishSecretRef:
      name: juicefs-sc-secret
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: plex-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: juicefs-sc
  selector:
    matchLabels:
      juicefs-name: movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tvshows
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: juicefs-sc
  selector:
    matchLabels:
      juicefs-name: tvshows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-all
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: juicefs-sc
  selector:
    matchLabels:
      juicefs-name: all
