apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: wildcard-delegation
  namespace: certificates
spec:
  delegations:
    - secretName: wildcard
      targetNamespaces:
      - "*"
