---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
  values:
    image:
      tag: 18-fpm-alpine
    nextcloud:
      host: "cloud.${SECRET_DOMAIN_ALT}"
      username: patrik
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-db-postgresql.nextcloud.svc.cluster.local
      database: nextcloud
      user: nextcloud
      existingSecret:
        enabled: true
        secretName: db-secret
        usernameKey: db-username
        passwordKey: postgresql-password
    cronjob:
      enabled: true
      schedule: "*/30 * * * *"
    persistence:
      enabled: true
      existingClaim: nextcloud-data
