# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: external-dns
type: Opaque
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:YurJwYS1KBw185/vEspqVtmxVkBITDqj+8yNx/8OPEN8QZ3uHplg5w==,iv:qjv/W8mS2tjVm+R2zHrvR2GZGMqf/673zgskmEkEhHc=,tag:RdwO65hUyHdBnyMHnwwwQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-07T09:23:00Z"
    mac: ENC[AES256_GCM,data:x9mpSeqqdsgsLvu5T+6Z9YH8uJ+y+zos0/63VZeEgP37orUmTmh2INyAg9IcDsZ/XT3r8wcCRdE5q0t/L930yLW0wWDTC50WWIUOOkOCDBcZ7pAaLb3aom0MTrmLzdNSJXUYlAjJhte2hIW/LO1fNBkGqr2KS5PV9z6i6PHVhIA=,iv:3inQQq2QkAtDkYUcM5u7UPVd7HCMZlI5jgjs4FqCwk4=,tag:xJqEq8p/ugUmFyRvzNxOkw==,type:str]
    pgp:
        - created_at: "2021-05-07T08:11:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+IDNKkyKZBFVg/mT0U1EB6GdgrVE7BzzdFiYZQV4EPY1d
            8O7Zf0BtBMkIyHVJeoEW0meWgDyxaoKGCv/wDtQeWiKSYnypiLSPnXnp44oLa8j2
            xHQrQVsHLlubeJXTm6CWm0Bv+VrYiFqTH572IwtNhbQzyYCnIhJ2j6Y+/Ix50Cv/
            /4inqmy2N5aAj5nL0K+RCB58NYj4INc4s7v+fhUyFecvKThVDfqwwyIYQ5CZk9n6
            WssO2pVQ40Pv+ma+ROIGYCYnA5iptCffzcRBiOUPfbxvkdj9rDbPpf2683eMFdvF
            DxpqjpdkQORtBU9NySAXxqlflXv2SSOjm8JBHRzaCA3Ew04nrePHeA54ABBAu7Jl
            k3cROUgzsCMANJLJ9BKD5llHzOy8Uytr+07NXQTpC9zmMjwgNq8ulm3KhqP793i6
            gSTyUcLvaY+2dTeOrp2v+q497AduwGXed4JBfWvBuU8t/sQ7qTQ7a9G3CG9UNtwC
            Sw+E+RfeoKq1OeBSBY5AQhrIgvhcu3kQNoLhHYwBbWH4XHVUAwLTLMZgioD5CKxR
            josyxlKKQa5tYIL7WEAy+8VfAvZhwsFopf/Y/TLvFjehIwHTkX4zwAcVnrV/GIOA
            jmLQ5bmoVrvf4sTcKv092NUaYu5Fpn3xS1S+MFS8nEq8KcOAdtnH7G1e3nH8wIXS
            XgEaV0YF1asQ2GBFqYKVyEFy1F6oAZacd13cCXjaW9cEZUy5yGXu+Z5Jg3q0c4Lj
            CA8dz7rzxw/6GGVB4UFsUdrxW1ask3Q4G3POAkrdChVXJm77mEyQ2TLSDq/A0ZM=
            =eiRC
            -----END PGP MESSAGE-----
          fp: 2C3E86E982BBE36AD0FBB0270B323237B39B6B5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
