---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webtrees-db
  namespace: webtrees
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: webtrees-db
    architecture: standalone
    auth:
      username: webtrees
      database: webtrees
      existingSecret: db-secret
    primary:
      persistence:
        size: 10Gi
