---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtrees-data
  namespace: webtrees
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: block
