---
- name: Install HWE kernel
  apt:
    name:
      - linux-generic-hwe-{{ ansible_distribution_version }}
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Reboot if kernel was updated and requested by the system
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting to update system kernel as needed' 
  args:
      removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true

- name: Wait for system to become reachable again
  wait_for_connection:
      delay: 5
      timeout: 600
