# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    NODE_NAME_01: ENC[AES256_GCM,data:Eapa28k=,iv:dBy5pH67g0R83+aPSgi/0jjqsw4/UmGiAbRROkDYlMs=,tag:UHY5wNXk8Z6Nny9Nd86f+g==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:xgkJ+GOGqdiB5KptUdc=,iv:vmoM6sgznysKVp3Qtuazu1gHGXAxEbuYy4omR1hvHRc=,tag:hfuBUAwz4GnFObZntYdduQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7qliy471Lg==,iv:GZqqVQR2kwNYMEe4LqZ6253XEtpiljJiNzPPpw0QHWI=,tag:Zx7cOrlmMeUHQoHbtykxvw==,type:str]
    SECRET_DOMAIN_ALT: ENC[AES256_GCM,data:iC731ge7oyyo,iv:T99FcuMLg8h8YLverNCTmRlLWeD6IwxZ+1hz6TJD3qE=,tag:q3FqwLxC5CQRfRNZeFWhcg==,type:str]
    SECRET_DOMAIN_DEV: ENC[AES256_GCM,data:GTn3GcjX+Nw=,iv:ZjajyfU9685vo1gAanYr30nO82S0ikfpE3w3YEeSYd0=,tag:8U3OIiqaa5SPgBvXf3h8Iw==,type:str]
    PRIVATE_IP: ENC[AES256_GCM,data:8u/ghYQKq5ERVj5n8w==,iv:NKZ7rwDW0b8YUR94hwrFT6sQszMR99R1M1cOzf+xWxo=,tag:CE/TN89LMN8ysVBlWhUApg==,type:str]
    PUBLIC_IP: ENC[AES256_GCM,data:DCMaGuZIcbT01BpgkA==,iv:xhxHP23avd2UP07JG9qh6t61tMn1sLynbttiJfnIeQY=,tag:u0cV/RDlSIOybD0ppanoqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-13T12:03:13Z"
    mac: ENC[AES256_GCM,data:YKzc0Ru9hSd10cQp4e7mVgbN/I+ekQkMv5Uhk5gMA161DkYWlhF5+VsdswQARk3iL6W4kg0SX6GMTOxI4QpiVyKaCjLqpeEhFmALYyWA8S17vQB93prAljvfNCHEOoXrdZSyJxdi/tXyZAgv6Uq2UX7+SYQKIoVUM6uieFEB9oU=,iv:llDWtgN//qGJ1wDPZJ0lBYg5Fu8tSjI5a3SB0oV6TE8=,tag:YnvV7O7E3pMxNi+M+x8jKw==,type:str]
    pgp:
        - created_at: "2021-05-07T06:34:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/+IfzqGbTOx3ZK0d2x4mBCLwJcXEccp8B7uc51vvca1Xct
            kMC+43jncgBSiaUfEOR2s/3MJfvfvzZezDRixjAkLEhdYyJN/D2bbBCbxicAxl05
            nACkNRHMcm/vAPq/LSm/H29VGr6WWPeEjd8bigqaj3EeEKtKfjkXnx0BqHZSUUmW
            BWXwIM1aHR2YOcWBpF26SE2AuQuug8j9w8bkzFsZu60kJDrWlOCGImaNCsZuNhry
            UUw5WU9sURE44gvbPE4SA7nuvd7X0TMbifY/ZKkaDkwaE6+kF9+wPTJHgXfM03x/
            9kUfKOK45NTK1WrCmQns5lCXrclwuKhEcedRIf4G3CX0jCHMMKW+yXq4IFMVF4gq
            Ko2S3MAUU+D5LqFHGIyW+E4UOPU5WBYT3364qBIcuFadwotT4Zp6xZ5Rv20FAws6
            UxfbAtmAL3LREySmhJBLhI6gZIfqmA4ynt1tqqzStruuiPFbrZigAeu6JwfWvaSI
            LVuz664vizyPOFGKgM4ZvVdcSebXw+OP/MqbhEditfVe6OUrXYBNvd11l0cwRpjq
            pe6W2dpyQ8EUOmqZLPByPWFsPFFf4QlgjsVWr0SkdB006QrNsq7ehsFIcerQTuIz
            4tjXV1YzTEQUTAkaJJThxSRGDRMccfmMQghGzCOKEV61HdJ86d16f6l4VBaSjEjS
            XAH5X25IuJE8J5JLa90+aG4GdbLiWyrG7SjZd5yQxzkwBwit/jLoYVREDxVwZgnt
            FHSEmXmnbB2U+nHJIvDn37RDqedzXLXbp3SBJwcHJUPgtLjnnaau1Q73xmeO
            =9P97
            -----END PGP MESSAGE-----
          fp: 2C3E86E982BBE36AD0FBB0270B323237B39B6B5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
