scw-dc5:
    vars:
        ansible_user: root
        ansible_become: true
        #tailscale_nic: tailscale0
        private_nic: enp1s0f0
        #ansible_tailscale_nic: ansible_{{ tailscale_nic }}
        ansible_private_nic: ansible_{{ tailscale_nic }}
        resolv_nameservers:
            - ENC[AES256_GCM,data:qCnPjdBtaxAunZ1z,iv:V3lEvJorOH7Np1rd4I1Jr9UsPBFI1GRW8tFlP0+PDSY=,tag:ARBpwK/LeNtNs649sCDhJg==,type:str]
            - ENC[AES256_GCM,data:ex5GUjBnmVHba3Imr+/T,iv:PEJuDRNKj0BFdsUfktv2xdqUtsVByuicFkNgTcwYuu0=,tag:mMzS1WuQJPQpO5Vct8vKaw==,type:str]
        resolv_search:
            - ENC[AES256_GCM,data:lpCWpi65Z0hEhSXvoPwVI0fszXoGK/sPLsquu8FN5yIP4/02XTo98xRw,iv:E6W29i3+ggfoS8u3/q53bYuD9Rtq4+mUMRQsWhQH3Pw=,tag:nqt1E9Y2BQoTfLnZ5GlXgA==,type:str]
        s3_backup:
            bucket: ENC[AES256_GCM,data:UJeEhK4L/G+7ALza,iv:mcrWoiED9aBpHo7Eae+3tMfwEZFOMSUcYl4A05RJ508=,tag:XsCkVDaEDKLZcnsHLs2SiQ==,type:str]
            access_key: ENC[AES256_GCM,data:lmC/gJ5VpcuP+AMgaMocsUWon+M=,iv:E/Tm5hpnkp8FIP/wm7JU/Lt1nXkG2LOOnvuFggJoGtM=,tag:BLnxyU9Mx9lYOPnUa3+e4A==,type:str]
            secret_key: ENC[AES256_GCM,data:/Q6iIhnxi9f4C4bj2C5b5mzTCXyK6qbMPcGqeTwwLg/inz7U,iv:Q0m58FSoJM62HGWSbIoKgyTBMy2r+yMxWojVKpGXvw8=,tag:WSbSCA4Y9JGDHlvTb9u8aA==,type:str]
            url: ENC[AES256_GCM,data:EtQPvJPNgrOCGwP0ZYo4tGzF+Q==,iv:IWUrkQ/vM1iM3GNPKJM5y5FtxboWCogasf5IKQqyeeg=,tag:ZHZCYCuulfNZyiaP0c9r7A==,type:str]
            region: fr-par
            gpg_passphrase: ENC[AES256_GCM,data:0xXN2zFmTK38P4XAag+UWgHz0w0=,iv:8mgqfD5mkr82LosDNsqkJBYG1UyZFwHrJSms6tYErTg=,tag:O/njP3G//edBHs0sjf18pg==,type:str]
    children:
        k8s-cluster:
            children:
                kube-master:
                    children:
                        dedicated:
                            hosts:
                                luffy:
                                    ansible_host: ENC[AES256_GCM,data:NsWM/GxaHJaSvEr/3w==,iv:uUR+LtDDtSBTLo+EN3lxy7v4+ch6qTkWwFNE9LqiPpU=,tag:kHgfzLlybzOnuksbBmIFqA==,type:str]
                kube-node: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-07T15:17:06Z"
    mac: ENC[AES256_GCM,data:ZFG0Nf+EHy0m3X+Mz2ujS60zXETWTbdICJUbd+VGoFUr0VImvMWXpjaUWYLIIBmQh684gdnIdzKKy++dWzU7EfvNSaMkkTXtEm+M2cXSW84gmxNxoHZrUyQiAbHMQXvmXo968SpNkNK5fqjB9BcCyBKHSNa2puHYumxVethQZ7U=,iv:zv546xqm6W72cEpJI2pUkMp4CEM2oCZ+c6BJ4vLg0mo=,tag:EO84fZUykMYPplwUnb+OGA==,type:str]
    pgp:
        - created_at: "2021-09-18T22:30:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAmrwDqT8IM4ehMHo7LO8F0abAP+kw+x/pR6liSbSKSnCq
            rLWaFtf+tedMlUPQtRn5t3N/OqoOSKdZSP5b6IIXbVJIDf0+b5s4tVAli4FITGYu
            kQ9ZdHuXoQVM1m2qoViNPRmBQSi8ZYlhXn96CeDINZXbuGAGOR/dsG1/BYpqiAnb
            gB97P7z2p3TZDlOWxLUkKuO7bUn7I8fJ8aX5qdnXyvNENj8MTnBlBrrUru6IXR9u
            JsKF0L7pqGXUn9SUkGuCn8znYvWAzIvoXcw70C3V0V5YvA1KZFRtfl80uunpGimT
            ufAxQzjEmYu6Z1mUckZbC2Ymo0n6+WUObJVwbHImtDhv9mddR/mKzPjNVcJ/l88n
            QP/GlMpGpr/xmtHR7QvUm/L9yqozYNpSGNqqzvoYxUGJcqbN8yblgqeEWIcKRnR8
            l6LYgNBhO8V2rZTuJo6S8SjXSjQ6nD+b4iraAfoytwrXlbibJIHRxDiehYXwHmql
            kPy7qTNWUSU2EnccoLjCELVmcST70IdUBlEzVajN/+KLNoVMTnQYpMNEZOBeEOIW
            yOfrFI9VNoiF5pTB31EbGkwCnq5HbgafNHabi0yt2nFvbyfyjygXVQuZUayNsA4m
            DI3et6icEEeiJEiivo0aWac9iwxkB/DYzO/yQl6+Rj7XNTvWldBIo0U83pm/OJHS
            XAHIsXtq1zRGphbdBa85T+ztGSKd192r9lSQ7PRMRM0KiUeOskaUJj0awtF0LIQq
            cmHZdQg+CXvcIMS3/B+/IB/aImZ69dsHbwYvjLnyJYElz0u1nLNP1YfZiLdp
            =5sYC
            -----END PGP MESSAGE-----
          fp: 2C3E86E982BBE36AD0FBB0270B323237B39B6B5B
    encrypted_regex: ^(ansible_host|subnet|gateway|s3_access_key|s3_secret_key|s3_bucket|s3_url|gpg_passphrase|access_key|secret_key|bucket|url|resolv_nameservers|resolv_search)$
    version: 3.7.1
