---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    global:
      storageClass: nextcloud-db
    replication:
      enabled: false
    existingSecret: db-secret
    postgresqlUsername: nextcloud
    postgresqlDatabase: nextcloud
    persistence:
      size: 10Gi
