---
apiVersion: v1
kind: Service
metadata:
  name: webtrees
  namespace: webtrees
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webtrees
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: webtrees
  namespace: webtrees
  annotations:
    cloudflare.com/expose: "true"
spec:
  ingressClassName: "contour"
  virtualhost:
    fqdn: "family.${SECRET_DOMAIN_ALT}"
    tls:
      secretName: certificates/wildcard
  routes:
  - services:
    - name: webtrees
      port: 80
