---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: torrent-config
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: torrent-watch
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: torrent-downloads
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: torrent-config
  local:
    path: /data/seedbox/torrent
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-watch
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: torrent-watch
  local:
    path: /data/torrent/watch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-downloads
spec:
  capacity:
    storage: 256Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: torrent-downloads
  local:
    path: /data/torrent/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-config
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: torrent-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-watch
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: torrent-watch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-downloads
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  storageClassName: torrent-downloads
