---
apiVersion: v1
kind: Service
metadata:
  name: torrent
  namespace: seedbox
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: torrent
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: torrent
  namespace: seedbox
  annotations:
    cloudflare.com/expose: "true"
spec:
  ingressClassName: "contour-internal"
  virtualhost:
    fqdn: "torrent.${SECRET_DOMAIN}"
    tls:
      secretName: certificates/wildcard
  routes:
  - services:
    - name: torrent
      port: 80
