---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://juicedata.github.io/juicefs-csi-driver
      chart: juicefs-csi-driver
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: juicefs-csi-driver
        namespace: flux-system
  values:
    storageClasses:
    - name: juicefs-sc
      enabled: false
