apiVersion: v1
stringData:
    api-key: ENC[AES256_GCM,data:afEJf6NH6RZUUgG74oDQaSfI41H4ig7R+pIBck+VaL0=,iv:W4yAx5LYNv9btrRHgkcKqWObaw2oJfdF+p7VFgYPdt4=,tag:wTQOXJe+xW+2sLKo22YDHQ==,type:str]
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-07T10:26:36Z"
    mac: ENC[AES256_GCM,data:p3Akl4kFEfuq+g0W3dX1cDlxI3Aa0MThphE2Aagfbr+dcTpW9LkUcUgR71GQtRYnmk3vI/fT5CF7N+hptpINWu8XBeTHlygpJ+3cAwXoquunySItCjPzoq90IazyVShinuWWn2dkMcyG2XQsbq4NHRE55Qt5ozL/af0n/UWtE/U=,iv:H+20E4V6GryP50LsIMpa0JKEeaQujdy2AFX43NjEhH0=,tag:vnyLpc5pNlRL2xaU1m9+SQ==,type:str]
    pgp:
        - created_at: "2021-05-07T10:26:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//TwwVhtY4MEmNLWtSZAUyT+rsr6MrcmIJM8+EtRE/xRyj
            ZhKFD5ukMVlW0wodRLOdhAwnlNbVO1tiZbInWJBYiV/5r1xaamzk4D553/3J4GxC
            uXxO4jELztWYnTSfoyjE2mtM5pt5Enq2NcscYxDNqX1nWH0XAqrAYqpr4dCs9hnp
            VXWny6h2nhQz2roeUsg95wSHnlp+i580lMkxwgoxgpC+GjDOBUm2WavI3uDKkrVa
            B5HB84Ejg+2k7eolUnY7jejtmRuehlzt2x9VwE5+hDKY2nmKzQfPXmyyDAXbL1ux
            8fLfaA6nbw66nStUWkCCfqgLyt89S1jdBemv1KwIgOFq3zdInh3wsRC1WKXZoJBT
            AxtvWnWbsX2GJeBoYWNBuhV4yzmB0hO6cUhBkWO9AsnwS2tvSDKK/Gi8BbNNlvKc
            IT2vHsy87De8C/9GNmhQp2ySMZDTAgpPZ3n+zmhQwExakLYh0IPOmBY23Vdpzaje
            1Fj50brPWSIJzNVXBBi+yyakh5yNUo30DiVEucJv9YEDoKiMU38DKyWj9LHsYyHd
            Zyy36lB8+nTsQDsj9dq4YmAPS2Q+k7KVraRMwzQyI5hESlKlklQYdKFzb3T7wJz+
            s7i90dhnwI46w9vfIFzUV6pg5R67hYcspf6qUIpHH8msQ1mjflSTBgjogM8L/Y3S
            XgEXNgn4Lc+GIy11hIKl8YtNyWhivOYY3qMKQ6Bik8mqRtwcPqu7I5b4yAD4yhlx
            bB125+cYzO38XYd/EQW+qgDC6Gw+HLyXfCh9yxYnTT6DaBSG7nNcCmnIne0mXSY=
            =6/1/
            -----END PGP MESSAGE-----
          fp: 2C3E86E982BBE36AD0FBB0270B323237B39B6B5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:M/Qwx9vBfnUIy1w6AFmUxzvyCgemKVeG5rZvrzER+IlY1kdO5sSnlljrXL7VLPhNICJJFDMMSAST1JOF,iv:Nafd2Nw19NRe1lFG0goXd5rnmICVgcSd7chvgWvrlpA=,tag:N58tMvzGjCJBtnXJGz7Iug==,type:str]
kind: Secret
metadata:
    name: datadog-auth-token
    namespace: datadog
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-07T10:26:36Z"
    mac: ENC[AES256_GCM,data:p3Akl4kFEfuq+g0W3dX1cDlxI3Aa0MThphE2Aagfbr+dcTpW9LkUcUgR71GQtRYnmk3vI/fT5CF7N+hptpINWu8XBeTHlygpJ+3cAwXoquunySItCjPzoq90IazyVShinuWWn2dkMcyG2XQsbq4NHRE55Qt5ozL/af0n/UWtE/U=,iv:H+20E4V6GryP50LsIMpa0JKEeaQujdy2AFX43NjEhH0=,tag:vnyLpc5pNlRL2xaU1m9+SQ==,type:str]
    pgp:
        - created_at: "2021-05-07T10:26:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//TwwVhtY4MEmNLWtSZAUyT+rsr6MrcmIJM8+EtRE/xRyj
            ZhKFD5ukMVlW0wodRLOdhAwnlNbVO1tiZbInWJBYiV/5r1xaamzk4D553/3J4GxC
            uXxO4jELztWYnTSfoyjE2mtM5pt5Enq2NcscYxDNqX1nWH0XAqrAYqpr4dCs9hnp
            VXWny6h2nhQz2roeUsg95wSHnlp+i580lMkxwgoxgpC+GjDOBUm2WavI3uDKkrVa
            B5HB84Ejg+2k7eolUnY7jejtmRuehlzt2x9VwE5+hDKY2nmKzQfPXmyyDAXbL1ux
            8fLfaA6nbw66nStUWkCCfqgLyt89S1jdBemv1KwIgOFq3zdInh3wsRC1WKXZoJBT
            AxtvWnWbsX2GJeBoYWNBuhV4yzmB0hO6cUhBkWO9AsnwS2tvSDKK/Gi8BbNNlvKc
            IT2vHsy87De8C/9GNmhQp2ySMZDTAgpPZ3n+zmhQwExakLYh0IPOmBY23Vdpzaje
            1Fj50brPWSIJzNVXBBi+yyakh5yNUo30DiVEucJv9YEDoKiMU38DKyWj9LHsYyHd
            Zyy36lB8+nTsQDsj9dq4YmAPS2Q+k7KVraRMwzQyI5hESlKlklQYdKFzb3T7wJz+
            s7i90dhnwI46w9vfIFzUV6pg5R67hYcspf6qUIpHH8msQ1mjflSTBgjogM8L/Y3S
            XgEXNgn4Lc+GIy11hIKl8YtNyWhivOYY3qMKQ6Bik8mqRtwcPqu7I5b4yAD4yhlx
            bB125+cYzO38XYd/EQW+qgDC6Gw+HLyXfCh9yxYnTT6DaBSG7nNcCmnIne0mXSY=
            =6/1/
            -----END PGP MESSAGE-----
          fp: 2C3E86E982BBE36AD0FBB0270B323237B39B6B5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
