---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-dns
spec:
  acme:
    email: "${SECRET_EMAIL}"
    privateKeySecretRef:
      name: cloudfalre-dns-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: "${SECRET_EMAIL}"
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
