---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bitwarden
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bitwarden
  local:
    path: /data/bitwarden
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: bitwarden
