---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: seedbox
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8989
  selector:
    app: sonarr
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonarr
  namespace: seedbox
  annotations:
    cloudflare.com/expose: "true"
spec:
  ingressClassName: "contour"
  virtualhost:
    fqdn: "series.${SECRET_DOMAIN}"
    tls:
      secretName: certificates/wildcard
    authorization:
      extensionRef:
        name: htpasswd
        namespace: contour-auth
  routes:
  - services:
    - name: sonarr
      port: 80
