---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-data
  namespace: znc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: block
