---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour-internal
  namespace: contour-internal
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: contour
      version: 8.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    nameOverride: contour-internal
    contour:
      manageCRDs: false
      ingressClass: "contour-internal"
    envoy:
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
      useHostPort: true
      containerPorts:
        http: 8080
        https: 8443
      useHostIP: true
      hostIPs:
        http: "${PRIVATE_IP}"
        https: "${PRIVATE_IP}"
