---
- block:
  - get_url:
      url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      dest: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"

  - apt_repository:
      repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
      state: absent
      update_cache: yes

  - apt_repository:
      repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main'
      state: present
      update_cache: yes

- name: Install kube-common packages
  apt:
    name:
      - "kubelet={{ kubernetes_version }}*"
      - "kubectl={{ kubernetes_version }}*"
      - "kubeadm={{ kubernetes_version }}*"
  register: apt_out
  ignore_errors: yes

- name: Handle kube-common install errors
  fail:
    msg: "{{ apt_out.stderr }}"
  when: "apt_out.rc | default(0) != 0 and 'Held packages were changed' not in apt_out.stderr"

- name: Hold kube-common packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "kubelet"
    - "kubectl"
    - "kubeadm"
