---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jackett
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jackett
  local:
    path: /data/seedbox/jackett
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${NODE_NAME_01}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: jackett
