---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: seedbox
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9117
  selector:
    app: jackett
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jackett
  namespace: seedbox
  annotations:
    cloudflare.com/expose: "true"
spec:
  ingressClassName: "contour"
  virtualhost:
    fqdn: "index.${SECRET_DOMAIN}"
    tls:
      secretName: certificates/wildcard
  routes:
  - services:
    - name: jackett
      port: 80
