---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaresolverr
  name: flaresolverr
  namespace: seedbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
      - image: ghcr.io/flaresolverr/flaresolverr:latest
        name: flaresolverr
        ports:
        - containerPort: 8191
          name: http
        env:
        - name: LOG_LEVEL
          value: "info"
