---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ombi
  name: ombi
  namespace: seedbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - image: ghcr.io/linuxserver/ombi:4.7.6
        name: ombi
        ports:
        - containerPort: 3579
          name: http
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        volumeMounts:
        - mountPath: "/config"
          name: ombi-config
      volumes:
      - name: ombi-config
        persistentVolumeClaim:
          claimName: ombi-config
