---
apiVersion: v1
kind: Service
metadata:
  name: ombi
  namespace: seedbox
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3579
  selector:
    app: ombi
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ombi
  namespace: seedbox
  annotations:
    cloudflare.com/expose: "true"
spec:
  ingressClassName: "contour"
  virtualhost:
    fqdn: "ombi.${SECRET_DOMAIN}"
    tls:
      secretName: certificates/wildcard
  routes:
  - services:
    - name: ombi
      port: 80
