---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hetzner-cloud-controller-manager
  namespace: kube-system
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:hetzner-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hetzner-cloud-controller-manager
    namespace: kube-system

---

# psp
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hetzner-cloud-controller-manager
spec:
  hostIPC: false
  hostPID: false
  hostNetwork: false
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsUser:
    rule: MustRunAs
    ranges:
      - max: 40801
        min: 40801
  runAsGroup:
    rule: MustRunAs
    ranges:
      - max: 40801
        min: 40801
  fsGroup:
    rule: MustRunAs
    ranges:
      - max: 40801
        min: 40801
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - max: 40801
        min: 40801
  volumes:
    - 'secret'
---

# Cluster role for psp usage
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hetzner-cloud-controller-manager
rules:
  - apiGroups:
      - extensions
      - policy
    resourceNames:
      - hetzner-cloud-controller-manager
    resources:
      - podsecuritypolicies
    verbs:
      - use
---

# Cluster role Binding for psp
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hetzner-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hetzner-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: hetzner-cloud-controller-manager
    namespace: kube-system
