# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: hetzner-cloud-controller-manager
    namespace: kube-system
stringData:
    robot_password: ENC[AES256_GCM,data:yf3VYIo3652bGyXqQJXBaoIeZmY=,iv:gIrbK+VdyOWKXIl2q66+En1bJZjp+rmPXJF0AxpHdBA=,tag:rF9HUMkhzlxE0KWIC8jScw==,type:str]
    robot_user: ENC[AES256_GCM,data:UmCU+QqhPfYnJ4WN,iv:Y43rszDZVsFOKjhkwgNnIB7M0VKNieTrKdPIfyef5/M=,tag:wO9lWClh/xI1vIQohKReDQ==,type:str]
    token: ENC[AES256_GCM,data:5Y6RI07Qqcfnck4Z0O21ULK0IN3r92/wRwjSvGICgnR468dmPBkjlrzVRWh3ze1lZtyb4j4MFbXIX/ECxrj+EQ==,iv:dZAS6PukNurLg+U0dPwF8mTTYTCUXH4Lw6Qn/KevCcQ=,tag:JEQ/rlZMVt+YjDYDlVJJ+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-07T07:58:46Z"
    mac: ENC[AES256_GCM,data:ZloHeTnKq1ORXzXdF2IvcfVNm2rZne/isXgYkiSPXOWUIW4jHbQzaka2qpATpAqHjuTga8KlYpxCA8SS9UParkfaDznN+3NYgGH0m9yShWga9s4UlI7x/rqkjx6dIKToMGJBxh2BgJvcwEtZEfkQAEnxZw3VbYWrGnqsp/Mvfhw=,iv:enS/W/CQku/cJt3SuEoy1JwjwqOs/M1VlezPmQHNpq0=,tag:ZNoQcQrJsN0IUqyqEvfmNA==,type:str]
    pgp:
        - created_at: "2021-05-07T07:58:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/9ErDPfFOhx4egiwg9D3tvxJY6cx27VJL8Ah/tiVmSnCOX
            xjHFzcGifpQnwTmrOWJi3C0uQ4UV0uznMT88XzqWcggHhetTTshyREPhQcQLYnh7
            OTg1Y4NA5jszxA88KaaD9iyRMN354qHd3RskrrJaiDEsEdeJsNGg4RuimmtNAg97
            7N4kFuYTGgy0k3F7szITlDi7Gmn8fW4Y/CEXvCiddHqAWQRd6ER0AF+MaMa/6qpm
            pEho3+x4JR5B+G1MEO1Miw07W49z21SNl41O6T/30hwAKr+aRO73HlZriAwI2OxT
            1XPviSTjs7hY28+ZOMKyj5fyu/N7oevXe+jplvTggUDTwVkcfl1uMdOp6Q4lohwS
            Wgnqdmr5CCh5zIgSk0qFWIzK5KV1zJC8HEesSSo9aHrQfJFwKmHSnK7Dn7HI1gi6
            caGlbLd09aVRCjHL75yL/6cattsYqtAGWAv5Z+e3W1GBLgXkGQMXESUMdkGMcjid
            BrzXD8JoNGsCJtlpsKsJ+0p2wEk+10hQrtgOWW1XfDZR8QeV0AlkJuk/qfzg7yhL
            QVAb6zFq2Pgr/gJv3TBJW4mmNgZocQaiZExpvHJlZkNBgibVNPQ4hOGS+VxPzzAY
            3SEuOun9GWp+qCYz+9PgpWsSxCAtKnJ3CmFSuH7ET1nBrV5HY/JQ9qoKIdAXSGXS
            XgEvsOhjGSdGXRblBJdthzzkfumojpZsBNVskSsqQ1hqzwq40Wr8q3oELhWovG1x
            Mc3ARddIM2Fbqg2WSdH6ihMvQlTX5sssdoEgH+1cK5KebgEtP4ijc4HZg4iorKA=
            =OfwG
            -----END PGP MESSAGE-----
          fp: 2C3E86E982BBE36AD0FBB0270B323237B39B6B5B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
