apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: ghcr.io/sh4d1/blog:ef742395d1be1fe66da1e13da0313325e44f979a-1620029398 # {"$imagepolicy": "flux-system:blog"}
        name: blog
        ports:
        - containerPort: 80
          name: http
