---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-blog-config
  namespace: blog
data:
  default.conf: |-
    server {
        listen       80;
        return 301 $scheme://${SECRET_DOMAIN}$request_uri;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redirect-blog
  name: redirect-blog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect-blog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redirect-blog
    spec:
      containers:
      - image: nginx:1.20-alpine
        name: redirect-blog
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-default
          subPath: default.conf
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: nginx-default
        configMap:
          name: redirect-blog-config
