---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: seedbox
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 7878
  selector:
    app: radarr
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: radarr
  namespace: seedbox
  annotations:
    cloudflare.com/expose: "true"
spec:
  ingressClassName: "contour-internal"
  virtualhost:
    fqdn: "movies.${SECRET_DOMAIN}"
    tls:
      secretName: certificates/wildcard
  routes:
  - services:
    - name: radarr
      port: 80
