- name: Install s3ql
  apt:
    name: s3ql
    state: present
- name: Create log dir
  file:
    path: "/var/log/s3ql/"
    state: directory
    mode: '0755'

- name: Create cache dirs
  file:
    path: "/var/cache/s3ql/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ s3ql }}"
- name: Template systemd files
  template:
    src: s3ql.service
    dest: /etc/systemd/system/s3ql-{{ item.name }}.service
    owner: root
    mode: '0644'
  loop: "{{ s3ql }}"
- name: Create auth files
  template:
    src: s3ql.authinfo
    dest: /etc/s3ql-{{ item.name }}.authinfo
    owner: root
    mode: '0600'
  loop: "{{ s3ql }}"
- name: Create mountpoint
  file:
    path: "{{ item.mountpoint }}"
    state: directory
    mode: '0755'
  loop: "{{ s3ql }}"
- name: Enable unit
  systemd:
    name: "s3ql-{{ item.name }}"
    state: started
    enabled: yes
  loop: "{{ s3ql }}"
