---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces
- cert-manager
- certificates
- contour
- contour-auth
- datadog
- external-dns
- hetzner-cloud-controller-manager
- metallb
- rook-ceph
