---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- podmonitor.yaml
configMapGenerator:
- name: flux-grafana-dashboards
  files:
  - control-plane.json
  - cluster.json
  options:
    labels:
      grafana_dashboard: flux-system
