---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: contour
      version: 4.3.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: contour
    contour:
      manageCRDs: false
    envoy:
      service:
        loadBalancerIP: "${SECRET_ENVOY_LB_IP}"
        externalTrafficPolicy: Cluster
      useHostPort: false
